--- 
before_install: 
  - |
      travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
      cd SDL2-2.0.8
      ./configure
      make
      sudo make install
dist: bionic
language: c
script: make
sudo: required
